---
name: "Setup JDK 25"
description: "Setup JDK 25"
runs:
  using: "composite"
  steps:
    - name: Setup JDK 25
      uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # V5.7.0
      with:
        java-version: '25'
        distribution: temurin
        cache: gradle
